- name: Install required software
  apt: 
    name: "apt-transport-https" 
    state: latest

- name: Update APT cache && Upgrade APT to the latest packages
  apt: 
    update_cache: yes 
    cache_valid_time: 3600

- name: Upgrade APT to the latest packages
  apt: 
    upgrade: safe
