---
# vars file for common

users:
  - { user: "tinion" , pass: "$6$tKYuuyn7$HZrpkgsT.lCpnRfaFblswl8sczPI5yygMKaNHGpfQn/JK1ShO.3UWVZD495WmfKa1.DHxC4T92ebnBYH4rynw0" , groups: "sudo"}

rsa_keys:
  - { comment: "tinion@tinion-devops" , user: "tinion" , key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC3k3+30okYU1i9i4HISZ8ur20SgXgP492sMyLclznE3dzGQDJbBsDyO5GBkqspwis7rKrT7fRWVBvT7eOcuWPECW70qLVTv6vHzjPC/eG1dJ4FqF/J4CeHB7wToMe7K1HF8zlIJbOK6JjHUFq93lDFH+pnnbBut+dvkRcqkeF1o8MB8YQoJEuVMBytFkGHeWMGBQ8A2e7W4T9HPOJ/+dpmpmXpUNWhiykyLJ8UPUxZmCN3O5A9w8/UTKMaIvK89Ja2f2yIgkf8JdPQx2jqNVRFlwX4zMnvwgg/TL91sdfBPAubTQyxdd22BoxhG0wtwVXvt7XS37EBtDCzS/3QwYjRQ7js8u99UaKJcnZ1+kSLXcHiosbQ+OmFmoJFV1q/GzeShC9UphavhFXxt9j8VrUZJXNZva6WM1vAKuhbbcNBUN/GzJr9x5LyQsUoFqoGiER+wd6ezxHxB6X33CmQB/iMx3QuTGEPR6rvQFlO8W07EUPIr8+iwCpEOY4o7bIQfIbUeSCemh+g7mL+kX75t90fiDE+KKjRW/FDOF/37+XCwHdg/cQenmDOyXdX1OVZmP6GTdlSxD9hDzkxUvXSxrRpx2aWZnGp6cQV5jMmAgM57Wc1ahgwYyWcG1ugenGpJs0OFRF9nICdOvNh+T5U+9RejMGEdzhJjYPTAhFAehi+IQ== tinion@LFR021670" }

packages:
  - vim
  - htop
  - build-essential 
  - libssl-dev 
  - libffi-dev 
  - python-dev
  - python-setuptools
  - python3-pip
  - ntp

PermitRootLogin:        "no"
PasswordAuthentication: "yes"
PermitEmptyPasswords:   "no"
AllowAgentForwarding:   "yes"
X11Forwarding:          "yes"
